  
language: node_js

node_js:
  - 8.2.1
dist: trusty
addons:
  chrome: stable
env:
  global:
    - CC_TEST_REPORTER_ID=df50324a2fd30f9dd12b8a747eb45f6be43ab1c88b348a6b1f683d7252fafd18
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build --debug

script:
  - nyc --reporter=lcov npm run coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false