    
name: Coverage test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  no-locations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile    
      - name: Coverage to Codeclimate
        uses: MartinNuc/codeclimate-action@2
        env:
          CC_TEST_REPORTER_ID: df50324a2fd30f9dd12b8a747eb45f6be43ab1c88b348a6b1f683d7252fafd18

  single-location:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile    
      - name: Coverage to Codeclimate
        uses: MartinNuc/codeclimate-action@2
        env:
          CC_TEST_REPORTER_ID: df50324a2fd30f9dd12b8a747eb45f6be43ab1c88b348a6b1f683d7252fafd18
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov

  multiple-locations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile    
      - name: duplicate coverage result
        run: yarn coverage && cp ${{github.workspace}}/coverage/lcov.info ${{github.workspace}}/coverage/lcov2.info
      - name: Coverage to Codeclimate
        uses: MartinNuc/codeclimate-action@2
        env:
          CC_TEST_REPORTER_ID: df50324a2fd30f9dd12b8a747eb45f6be43ab1c88b348a6b1f683d7252fafd18
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
            ${{github.workspace}}/coverage/lcov2.info:lcov
