name: build
on:
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - app/lambda/aws-app/src/*
      - app/lambda/aws-app/__tests__/*
      - '*.json'
      - yarn.lock
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn build
    - uses: paambaati/codeclimate-action@v2.5.7
      env:
        CC_TEST_REPORTER_ID: df50324a2fd30f9dd12b8a747eb45f6be43ab1c88b348a6b1f683d7252fafd18
      with:
        coverageCommand: yarn coverage